export const sectionOne = {
    id: 'services',
    type: 1,
    lightBg: false,
    lightText: true,
    lighTextDesc: true,
    title1: '',
    p1: '',
    title2: '',
    p2: '',
    title3: '',
    p3: '',
    Icon1: require('../../img/services/adm.jpeg').default,
    Icon2: require('../../img/services/adm2.jpeg').default,
    Icon3: require('../../img/services/ren.jpeg').default,
    alt: 'Icon',
    dark: false,
    primary: true,
    darkText: false
};
export const sectionTwo = {
    id: 'services2',
    type: 2,
    lightBg: false,
    lightText: true,
    lighTextDesc: true,
    title1: '',
    p1: '',
    title2: 'Bienes Raíces',
    p2: '',
    title3: '',
    p3: '',
  
    Icon1: require('../../img/services/ren2.jpeg').default,
    Icon2: require('../../images/svg-6.svg').default,
    Icon3: require('../../img/services/com.jpeg').default,
    alt: 'Icon',
    dark: false,
    primary: true,
    darkText: false
};
export const sectionThree = {
    id: 'services3',
    type: 1,
    lightBg: false,
    lightText: true,
    lighTextDesc: true,
    title1: 'Administración de Rentas',
    p1: '',
    Button1: true,
    title2: 'Compra Venta de Inmuebles',
    p2: '',
    Button2: true,
    title3: 'Renta de Departamentos',
    p3: '',
    Button3: true,
    Icon1: require('../../img/services/adm.jpeg').default,
    Icon11: require('../../img/services/adm2.jpeg').default,
   // Icon2: require('../../img/services/com2.png').default,
    Icon2: require('../../img/services/com.jpeg').default,
    Icon22: require('../../img/services/com.jpeg').default,
    Icon3: require('../../img/services/ren.jpeg').default,
    Icon33: require('../../img/services/ren2.jpeg').default,
    alt: 'Icon',
    dark: false,
    primary: true,
    darkText: false
};

